# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    #permissions:
    #  contents: read
    #  packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Build with Maven
      run: |
        ./build.sh
        ls -R .

    - name: publish artifact to github
      uses: actions/upload-artifact@v4
      with:
        name: sign
        retention-days: 5
        compression-level: 0
        path: |
          target/*.jar
          testkey.x509.pem
          testkey.pk8
